export const DEVICE_GET_INTEGRITY = { METHOD: "POST", URL: "/device/mobile-get-integrity" };
export const CLIENT_CHECK_NUMBER_LOGIN = { METHOD: "POST", URL: "/client/mobile/check-number" };
export const CLIENT_REGISTER = { METHOD: "POST", URL: "/client/mobile/register" };
export const CLIENT_REGISTER_EMAIL = { METHOD: "POST", URL: "/client/register-email" };
export const CLIENT_REGISTER_CONFIRM = { METHOD: "POST", URL: "/client/mobile/register-confirm" };
export const CLIENT_AUTH_PASSWORD = { METHOD: "POST", URL: "/client/connect-password" };
export const CLIENT_RETRIEVE_PASSWORD = { METHOD: "POST", URL: "/client/retrieve-password" };
export const CLIENT_CHECK_CODE_RETRIEVE_PASSWORD = { METHOD: "POST", URL: "/client/check-code-retrieve-password" };
export const CLIENT_RESET_PASSWORD = { METHOD: "POST", URL: "/client/reset-password"};
export const USER_CHECK_OGS = { METHOD: "POST", URL: "/profile/exist" };
export const PROFILE_CREATE_PIN = { METHOD: "POST", URL: "/profile/create-pin"};
export const PROFILE_CHECK_PIN = { METHOD: "POST", URL: "/profile/check-pin"};
export const PROFILE_GET_BASE = { METHOD: "POST", URL: "/profile/get-base"};
export const PROFILE_CREATE_BIFLUX = { METHOD: "POST", URL: "/profile/create-biflux" }
export const PROFILE_JOIN_FLUX = { METHOD: "POST" , URL: "/profile/join-flux" }
export const PROFILE_EJECT_FLUX = { METHOD: "POST" , URL: "/flux/eject" }
export const PROFILE_NOTIFICATIONS_SUBSCRIPTION = { METHOD: "POST" , URL: "/profile/notifications-subscription" }
export const FLUX_SEND_MESSAGE = { METHOD: "POST" , URL: "/flux/send-message" }
